package view;

import control.ClientCtr;
import dto.FriendDTO;
import dto.RequestDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ObjectWrapper;

public class RequestFrm extends javax.swing.JDialog {

    /**
     * Creates new form RequestFrm
     */
    private ClientCtr mySocket;
    private Long id;
    private ArrayList<FriendDTO> users;
    private int selectedIndex = -1;
    private ArrayList<RequestDTO> requests = new ArrayList<>();

    public RequestFrm(java.awt.Frame parent, boolean modal, ClientCtr mySocket, Long id) {
        super(parent, modal);
        initComponents();
        this.mySocket = mySocket;
        this.id = id;
//        acceptBtn.setEnabled(false);
        declineBtn.setEnabled(false);

        getRequests();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    void getRequests() {
        this.mySocket.sendData(new ObjectWrapper(ObjectWrapper.GET_REQUESTS, id));
        receiveDataFromServer();
    }

    private void receiveDataFromServer() {
        ObjectWrapper data = mySocket.receiveData();
        if (data.getPerformative() == ObjectWrapper.REPLY_GET_REQUESTS) {
            this.requests = (ArrayList<RequestDTO>) data.getData();
            mapToTable();
        }

        if (data.getPerformative() == ObjectWrapper.REPLY_CONFIRM_FRIEND) {
            RequestDTO requestDTO = (RequestDTO) data.getData();
            if (!requestDTO.equals(null)) {
                getRequests();
                mapToTable();
            }
        }

        if (data.getPerformative() == ObjectWrapper.REPLY_DECLINE_FRIEND) {
            String mess = (String) data.getData();
            if (mess.equals("ok")) {
                getRequests();
                mapToTable();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error in declining request");
            }
        }

        if (data.getPerformative() == ObjectWrapper.REPLY_ADD_FRIEND) {
            Long id = (Long) data.getData();
            if (id.equals(this.id)) {
                getRequests();
                mapToTable();
            }
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestTbl = new javax.swing.JTable();
        usernameTxt = new javax.swing.JLabel();
        declineBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Requests");

        requestTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Requests"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        requestTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(requestTbl);

        declineBtn.setText("Decline");
        declineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(148, 148, 148)
                        .addComponent(declineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usernameTxt)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(declineBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(usernameTxt)
                        .addGap(0, 117, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void requestTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestTblMouseClicked
        this.selectedIndex = requestTbl.getSelectedRow();
//        acceptBtn.setEnabled(true);
        declineBtn.setEnabled(true);
        if (this.selectedIndex != -1 && this.requests.size() > 0) {
            usernameTxt.setText(requests.get(selectedIndex).getUsername());
        }
    }//GEN-LAST:event_requestTblMouseClicked

    private void declineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineBtnActionPerformed
        if (selectedIndex != -1) {
            Long friendId = requests.get(this.selectedIndex).getFriendId();
            mySocket.sendData(new ObjectWrapper(ObjectWrapper.DECLINE_FRIEND, requests.get(this.selectedIndex).getFriendId()));
            receiveDataFromServer();
        }
    }//GEN-LAST:event_declineBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequestFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequestFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequestFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequestFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RequestFrm dialog = new RequestFrm(new javax.swing.JFrame(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void mapToTable() {
        if (requests.size() >= 0) {
            String columns[] = {"Stt", "Username"};
            String[][] values = new String[requests.size()][columns.length];
            for (int i = 0; i < requests.size(); i++) {
                values[i][0] = i + 1 + "";
                values[i][1] = requests.get(i).getUsername() + "";
            }
            DefaultTableModel table = new DefaultTableModel(values, columns) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            requestTbl.setModel(table);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton declineBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable requestTbl;
    private javax.swing.JLabel usernameTxt;
    // End of variables declaration//GEN-END:variables
}
